config/routes.rb
OhjelmistotekniikanLabrat::Application.routes.draw do

  root :to => 'testRunner#selectDevice'

  
  match 'tests' => 'testRunner#displayTests', :as => 'select_test'
  match 'save' => 'testResult#saveResult'
  match 'devices' => 'testRunner#selectDevice', :as => 'select_device'
  match 'showPatchResult' => 'testResult#showPatchResult', :as => 'show_patch_result'
  match 'run' => 'testRunner#run'
  match 'results' => 'testResult#showResultNumbers'
end

app/models/test_result.rb
class TestResult < ActiveRecord::Base
  
  validates_presence_of :duration, :name, :executed, :framework, :device, :browser
  before_validation :setExecutedTime
  
  def setExecutedTime
    self.executed = DateTime.current()
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :getDevice
  
  private
  
  def getDevice
    device = params[:device] if params[:device]
    device = session[:device] if (session[:device] and device.nil?)
    unless device.nil?
      session[:device] = device
    end
  end
  
end

app/controllers/test_result_controller.rb
class TestResultController < ApplicationController
  
  def saveResult
    success = false;
    
    unless params["error"]
      parameters = {
        :duration => params["duration"],
        :name => params["name"],
        :elements => params["elements"],
        :description => params["description"],
        :framework => params["framework"],
        :device => params["device"],
        :browser => params["browser"]
      }
      result = TestResult.new(parameters)
      success = result.save
    end
    
    if session[:patchResults]
      css_class = "fail"
      css_class = "success" if success
      session[:patchResults][session[:testsToRun]] = {:index => session[:testsToRun], :success => success, :class => css_class, :duration => params["duration"]}
    end
    
    if session[:testsToRun] < 1
      logger.info "Finished test patch, showing results"
      puts "Finished test patch, showing results"
      redirect_to show_patch_result_url, :success => success
    else
      logger.info "Finished test, running next"
      puts "Finished test, running next"
      redirect_to :controller => 'testRunner', :action => 'run', :success => success, :partial => params["partial"]
    end
  end
  
  def showPatchResult
    @patch_results = session[:patchResults]
    duration = 0
    @patch_results.each do |result|
      duration += Integer(result[:duration])
    end
    @average_duration = duration/@patch_results.length
  end
  
  def showResultNumbers
    @insertion_Android = insertion(androidBrowserResults())
    @insertion_iPhone = insertion(iPhoneSafariResults())
    
    @deletion_Android = deletion(androidBrowserResults())
    @deletion_iPhone = deletion(iPhoneSafariResults())
    
    @modify_Android = modify(androidBrowserResults())
    @modify_iPhone = modify(iPhoneSafariResults())
    
    @finding_Android = finding(androidBrowserResults())
    @finding_iPhone = finding(iPhoneSafariResults())
  end
  
  
  private
  
  # TESTS
  
  def insertion(set)
    results = []
    3.times do |i|
      elements = 2000 if i==0
      elements = 4000 if i==1
      elements = 8000 if i==2
      3.times do |j|
        framework = "jQuery" if j==0
        framework = "Mootools" if j==1
        framework = "Prototype" if j==2
        result = set.find(:all, :conditions => {:name => "Insertion", :elements => elements, :framework => framework})
        results.push(resultHelper(result, elements, framework))
      end
    end
    return results
  end
  
  def deletion(set)
    results = []
    3.times do |i|
      elements = 2000 if i==0
      elements = 4000 if i==1
      elements = 8000 if i==2
      3.times do |j|
        framework = "jQuery" if j==0
        framework = "Mootools" if j==1
        framework = "Prototype" if j==2
        result = set.find(:all, :conditions => {:name => "Deletion", :elements => elements, :framework => framework})
        results.push(resultHelper(result, elements, framework))
      end
    end
    return results
  end
  
  def modify(set)
    results = []
    3.times do |i|
      elements = 2000 if i==0
      elements = 4000 if i==1
      elements = 8000 if i==2
      3.times do |j|
        framework = "jQuery" if j==0
        framework = "Mootools" if j==1
        framework = "Prototype" if j==2
        result = set.find(:all, :conditions => {:name => "Modify", :elements => elements, :framework => framework})
        results.push(resultHelper(result, elements, framework))
      end
    end
    return results
  end
  
  def finding(set)
    results = []
    3.times do |i|
      elements = 1000 if i==0
      elements = 1250 if i==1
      elements = 1500 if i==2
      3.times do |j|
        framework = "jQuery" if j==0
        framework = "Mootools" if j==1
        framework = "Prototype" if j==2
        result = set.find(:all, :conditions => {:name => "Finding", :elements => elements, :framework => framework})
        results.push(resultHelper(result, elements, framework))
      end
    end
    return results
  end
  
  # DEVICES
  
  def androidBrowserResults
    return TestResult.where('browser LIKE ? AND device LIKE ?', '%Safari%', '%Android%')
  end
  
  def iPhoneSafariResults
    return TestResult.where('browser LIKE ? AND device LIKE ?', '%Safari%', '%iPhone%')
  end
  
  def androidOperaResults
    return TestResult.where('browser LIKE ? AND device LIKE ?', '%Opera%', '%Android%')
  end
  
  def iPhoneOperaResults
    return TestResult.where('browser LIKE ? AND device LIKE ?', '%Opera%', '%iPhone%')
  end
  
  def n95Results
    return TestResult.where('device LIKE ?', '%N95%')
  end
  
  def resultHelper (result, elements, framework)
    durations = []
    result.select { |res| durations.push(res['duration']) }
    
    deviation = durations.standard_deviation
    average = durations.average
    
    offliers = result.select { |res| ((res['duration']-average).abs > 3*deviation) }
    offlier_durations = []
    good_results = result - offliers
    good_results.delete(offliers)
    good_results.select { |res| offlier_durations.push(res['duration']) }
    
    obj = {"framework" => framework, "elements" => elements, "results" => result.length, "deviation" => deviation, "average" => average, "offliers" => offliers, "offlier_average" => offlier_durations.average}
    return obj
  end
  
end


module Enumerable

    def sum
      self.inject(0){|accum, i| accum + i }
    end

    def mean
      self.sum/self.length.to_f
    end

    def sample_variance
      m = self.mean
      sum = self.inject(0){|accum, i| accum +(i-m)**2 }
      sum/(self.length - 1).to_f
    end

    def standard_deviation
      return Math.sqrt(self.sample_variance)
    end
    
    def average
      return self.inject(0.0) { |sum, el| sum + el } / self.size
    end

end

app/controllers/test_runner_controller.rb
class TestRunnerController < ApplicationController
  
  def selectDevice

  end
  
  def displayTests
    logger.info "Displaying tests and setting test num to 50"
    puts "Displaying tests and setting test num to 50"
    @last_was_success = nil
    unless params["success"].nil?
      @last_was_success = params["success"]
    end
    session[:testsToRun] = 50
    session[:patchResults] = Array.new
  end
  
  def run
    logger.info "Ran a test"
    puts "Ran a test"
    @partial_name = params["partial"]
    logger.debug "param elements: " << params["elements"].to_s
    logger.debug "condition: " << (session[:numberOfElements].nil? or params["elements"].to_i != session[:numberOfElements]).to_s
    if (session[:numberOfElements].nil? or (!params["elements"].nil? and params["elements"].to_i != session[:numberOfElements]))
      session[:numberOfElements] = params["elements"].to_i
    end
    @numberOfElements = session[:numberOfElements]
    session[:testsToRun] -= 1
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_result_helper.rb
module TestResultHelper
end

app/helpers/test_runner_helper.rb
module TestRunnerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OhjelmistotekniikanLabrat</title>
  <script type="text/javascript" charset="utf-8">
  	var selectedDevice = "<%= session[:device] or 'null' %>";
  </script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :javascript %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/test_result/_result_table.html.erb
<table>
	<caption><%= caption %></caption>
	<tr>
		<th>Framework</th>
		<th>Results</th>
		<th>Average</th>
		<th>Deviation</th>
		<th>Offliers</th>
		<th>Offlier avg</th>
		<th>Acceptable</th>
	</tr>
<% (results.select {|res| res["elements"] == elements }).each do |result| %>
	<tr>
		<td><%= result["framework"] %></td>
		<td><%= result["results"] %></td>
		<td><%= sprintf('%.2f', result["average"]) %></td>
		<td><%= sprintf('%.2f', result["deviation"]) %></td>
		<td><%= result["offliers"].length %></td>
		<td><%= sprintf('%.2f', result["offlier_average"]) %></td>
		<td><%= result["results"] - result["offliers"].length %></td>
	</tr>
<% end %>
</table>

app/views/test_result/showPatchResult.html.erb
<div class='nav_button'><%= link_to "<< All tests", select_test_path %></div>
<h1>Results</h1>


<div id="results" style='margin-left: 20px;'>
	<table>
		<tr>
			<th>duration</th>
			<th>saved?</th>
		</tr>
		
<% @patch_results.each do |result| %>
	<tr class='<%= result[:class] %>'>
		<td style='font-weight: bold;'><%= result[:duration] %></td>
		<td><%= result[:success] %></td>
	</tr>
<% end %>
		<tr>
			<td style='border-top: 1px solid black;'><%= @average_duration %></td>
			<td></td>
		</tr>
	</table>
</div>

app/views/test_result/showResultNumbers.html.erb
<style>
	table {
		margin: 30px;
		font-style: italic;
	}
	
	table caption {
		font-size: 14pt;
		font-style: normal;
	}
</style>


<h1>Insertion</h1>

<h2>Android Browser</h2>
<div>
	<%= render "result_table", :caption => "Insertion 2000", :results => @insertion_Android, :elements => 2000 %>
	<%= render "result_table", :caption => "Insertion 4000", :results => @insertion_Android, :elements => 4000 %>
	<%= render "result_table", :caption => "Insertion 8000", :results => @insertion_Android, :elements => 8000 %>
	<div style='clear:left;'></div>
</div>

<h2>iPhone Safari</h2>
<div>
	<%= render "result_table", :caption => "Insertion 2000", :results => @insertion_iPhone, :elements => 2000 %>
	<%= render "result_table", :caption => "Insertion 4000", :results => @insertion_iPhone, :elements => 4000 %>
	<%= render "result_table", :caption => "Insertion 8000", :results => @insertion_iPhone, :elements => 8000 %>
	<div style='clear:left;'></div>
</div>



<h1>Deletion</h1>

<h2>Android Browser</h2>
<div>
	<%= render "result_table", :caption => "Deletion 2000", :results => @deletion_Android, :elements => 2000 %>
	<%= render "result_table", :caption => "Deletion 4000", :results => @deletion_Android, :elements => 4000 %>
	<%= render "result_table", :caption => "Deletion 8000", :results => @deletion_Android, :elements => 8000 %>
	<div style='clear:left;'></div>
</div>

<h2>iPhone Safari</h2>
<div>
	<%= render "result_table", :caption => "Deletion 2000", :results => @deletion_iPhone, :elements => 2000 %>
	<%= render "result_table", :caption => "Deletion 4000", :results => @deletion_iPhone, :elements => 4000 %>
	<%= render "result_table", :caption => "Deletion 8000", :results => @deletion_iPhone, :elements => 8000 %>
	<div style='clear:left;'></div>
</div>



<h1>Modify</h1>

<h2>Android Browser</h2>
<div>
	<%= render "result_table", :caption => "Modify 2000", :results => @modify_Android, :elements => 2000 %>
	<%= render "result_table", :caption => "Modify 4000", :results => @modify_Android, :elements => 4000 %>
	<%= render "result_table", :caption => "Modify 8000", :results => @modify_Android, :elements => 8000 %>
	<div style='clear:left;'></div>
</div>

<h2>iPhone Safari</h2>
<div>
	<%= render "result_table", :caption => "Modify 2000", :results => @modify_iPhone, :elements => 2000 %>
	<%= render "result_table", :caption => "Modify 4000", :results => @modify_iPhone, :elements => 4000 %>
	<%= render "result_table", :caption => "Modify 8000", :results => @modify_iPhone, :elements => 8000 %>
	<div style='clear:left;'></div>
</div>




<h1>Finding</h1>

<h2>Android Browser</h2>
<div>
	<%= render "result_table", :caption => "Finding 1000", :results => @finding_Android, :elements => 1000 %>
	<%= render "result_table", :caption => "Finding 1250", :results => @finding_Android, :elements => 1250 %>
	<%= render "result_table", :caption => "Finding 1500", :results => @finding_Android, :elements => 1500 %>
	<div style='clear:left;'></div>
</div>

<h2>iPhone Safari</h2>
<div>
	<%= render "result_table", :caption => "Finding 1000", :results => @finding_iPhone, :elements => 1000 %>
	<%= render "result_table", :caption => "Finding 1250", :results => @finding_iPhone, :elements => 1250 %>
	<%= render "result_table", :caption => "Finding 1500", :results => @finding_iPhone, :elements => 1500 %>
	<div style='clear:left;'></div>
</div>

app/views/test_runner/_test_jquery_delete.html.erb
<% content_for :javascript do %>
	<%= javascript_include_tag "frameworks/jquery-1.7.1.js" %>
	<% #<%= javascript_include_tag "frameworks/mootools-core-1.4.4-full-nocompat.js" %>
	<% #<%= javascript_include_tag "frameworks/prototype_1_7_0.js" %>
<% end %>

<script>
  function executeTest(elements) {
	var startTime = new Date().getTime();
	for(var i = 0; i < elements.length; i++) {
		elements[i].detach();
	}
	var endTime = new Date().getTime();
	return endTime - startTime;
  }
  
  jQuery(document).ready(function() {
	var $body = jQuery('body');
	for (var i = 0; i < testData.elements; i++) {
		jQuery($body[0]).append("<div>Example</div>");
	}
	
	var elements = $body.find("div");
	for(var i=0; i < elements.length; i++) {
		elements[i] = jQuery(elements[i]);
	}
	
	var executionTime = executeTest(elements);
	
	testData.duration = executionTime;
	testData.name = "Deletion";
	testData.framework = "jQuery";
	testHelper.finished();
  });
</script>

app/views/test_runner/_test_jquery_finding.html.erb
<% content_for :javascript do %>
	<%= javascript_include_tag "frameworks/jquery-1.7.1.js" %>
	<% #<%= javascript_include_tag "frameworks/mootools-core-1.4.4-full-nocompat.js" %>
	<% #<%= javascript_include_tag "frameworks/prototype_1_7_0.js" %>
<% end %>

<script>
  function executeTest(targetClasses) {
    var bodyElement = $('body')[0];
	var startTime = new Date().getTime();
	
	for (var i = 0; i < targetClasses.length; i++) {
		var $elem = $(targetClasses[i]);
	}
	
	var endTime = new Date().getTime();
	
	return endTime - startTime;
  }
  
  $(document).ready(function() {
	var bodyElement = $('body')[0];
	var targetClasses = [];
	for (var i = 0; i < testData.elements; i++) {
		$(bodyElement).append("<div class='target_"+i+"'>Example</div>");
		targetClasses.push(".target_" + i);
	}
	
	var executionTime = executeTest(targetClasses);

	testData.duration = executionTime;
	testData.name = "Finding";
	testData.framework = "jQuery";
	testHelper.finished();
  });
</script>

app/views/test_runner/_test_jquery_modify.html.erb
<% content_for :javascript do %>
	<%= javascript_include_tag "frameworks/jquery-1.7.1.js" %>
	<% #<%= javascript_include_tag "frameworks/mootools-core-1.4.4-full-nocompat.js" %>
	<% #<%= javascript_include_tag "frameworks/prototype_1_7_0.js" %>
<% end %>

<script>
  function executeTest(colors) {
	var $elem = $("body").find("div");
	var startTime = new Date().getTime();
	for(var i = 0; i < colors.length; i++) {
		$elem.css('background', colors[i]);
	}
	var endTime = new Date().getTime();
	return endTime - startTime;
  }
  
  jQuery(document).ready(function() {
	var $body = jQuery('body');
	jQuery($body[0]).append("<div>Example</div>");
	var colors = testHelper.generateColors(testData.elements);
	var executionTime = executeTest(colors);
	
	testData.duration = executionTime;
	testData.name = "Modify";
	testData.framework = "jQuery";
	testHelper.finished();
  });
</script>

app/views/test_runner/_test_mootools_delete.html.erb
<% content_for :javascript do %>
	<% #<%= javascript_include_tag "frameworks/jquery-1.7.1.js" %>
	<%= javascript_include_tag "frameworks/mootools-core-1.4.4-full-nocompat.js" %>
	<% #<%= javascript_include_tag "frameworks/prototype_1_7_0.js" %>
<% end %>

<script>
  function executeTest(elements) {
	var time_start = (new Date()).getTime();
	for(var i = 0; i < elements.length; i++) {
		elements[i].dispose();
	}
	var time_finish = (new Date()).getTime();
	return time_finish-time_start
  }
  

  window.addEvent('domready', function() {
	var elements = []
	for(var i=0; i<testData.elements; i++) {
		var elem = new Element('div', {html: 'Example'});
		elements.push(elem);
		(elem).inject(document.body);
	}
	
	var executionTime = executeTest(elements);
	testData.duration = executionTime;
	testData.name = "Deletion";
	testData.framework = "Mootools";
	testHelper.finished();
  });
</script>

app/views/test_runner/_test_mootools_finding.html.erb
<% content_for :javascript do %>
	<% #<%= javascript_include_tag "frameworks/jquery-1.7.1.js" %>
	<%= javascript_include_tag "frameworks/mootools-core-1.4.4-full-nocompat.js" %>
	<% #<%= javascript_include_tag "frameworks/prototype_1_7_0.js" %>
<% end %>

<script>
  function executeTest(targetClasses) {
	var startTime = new Date().getTime();
	
	for (var i = 0; i < targetClasses.length; i++) {
		var $elem = $$(targetClasses[i]);
	}
	
	var endTime = new Date().getTime();
	
	return endTime - startTime;
  }
  
  window.addEvent('domready', function() {
	var targetClasses = [];
	
	for (var i = 0; i < testData.elements; i++) {
	    (new Element('div', {html: 'Example', 'class': 'target_' + i})).inject(document.body)
		targetClasses.push(".target_" + i);
	}
	
	var executionTime = executeTest(targetClasses);

	testData.duration = executionTime;
	testData.name = "Finding";
	testData.framework = "Mootools";
	testHelper.finished();
  });
</script>

app/views/test_runner/_test_mootools_insertion.html.erb
<% content_for :javascript do %>
	<% #<%= javascript_include_tag "frameworks/jquery-1.7.1.js" %>
	<%= javascript_include_tag "frameworks/mootools-core-1.4.4-full-nocompat.js" %>
	<% #<%= javascript_include_tag "frameworks/prototype_1_7_0.js" %>
<% end %>

<script>
  function executeTest() {
	var time_start = (new Date()).getTime();
	for(var i=0; i<testData.elements; i++) {
		(new Element('div', {html: 'Example'})).inject(document.body);
	}
	var time_finish = (new Date()).getTime();
	return time_finish-time_start
  }
  

  window.addEvent('domready', function() {
	var executionTime = executeTest();

	testData.duration = executionTime;
	testData.name = "Insertion";
	testData.framework = "Mootools";
	testHelper.finished();
  });
</script>

app/views/test_runner/_test_mootools_modify.html.erb
<% content_for :javascript do %>
	<% #<%= javascript_include_tag "frameworks/jquery-1.7.1.js" %>
	<%= javascript_include_tag "frameworks/mootools-core-1.4.4-full-nocompat.js" %>
	<% #<%= javascript_include_tag "frameworks/prototype_1_7_0.js" %>
<% end %>

<script>
  function executeTest(colors) {
    var $elem = $$("body div");
	var startTime = new Date().getTime();
	for(var i = 0; i < colors.length; i++) {
		$elem.setStyle('background', colors[i]);
	}
	var endTime = new Date().getTime();
	return endTime - startTime
  }
  

  window.addEvent('domready', function() {
	(new Element('div', {html: 'Example'})).inject(document.body);
	var colors = testHelper.generateColors(testData.elements);
	var executionTime = executeTest(colors);

	testData.duration = executionTime;
	testData.name = "Modify";
	testData.framework = "Mootools";
	testHelper.finished();
  });
</script>

app/views/test_runner/_test_prototype_delete.html.erb
<% content_for :javascript do %>
	<% #<%= javascript_include_tag "frameworks/jquery-1.7.1.js" %>
	<% #<%= javascript_include_tag "frameworks/mootools-core-1.4.4-full-nocompat.js" %>
	<%= javascript_include_tag "frameworks/prototype_1_7_0.js" %>
<% end %>

<script>
  function executeTest(elements) {
	var startTime = new Date().getTime();
	for (var i = 0; i < elements.length; i++) {
		elements[i].remove();
	}
	var endTime = new Date().getTime();
	return endTime - startTime;
  }

  document.observe('dom:loaded', function() {
	var bodyElement = $$('body')[0];
	var elements = [];
	for (var i = 0; i < testData.elements; i++) {
	    var element = new Element("div").update("Example");
		elements.push(element)
		bodyElement.insert(element);
	}
	
	var executionTime = executeTest(elements);

	testData.duration = executionTime;
	testData.name = "Deletion";
	testData.framework = "Prototype";
	testHelper.finished();
  });
</script>

app/views/test_runner/_test_prototype_finding.html.erb
<% content_for :javascript do %>
	<% #<%= javascript_include_tag "frameworks/jquery-1.7.1.js" %>
	<% #<%= javascript_include_tag "frameworks/mootools-core-1.4.4-full-nocompat.js" %>
	<%= javascript_include_tag "frameworks/prototype_1_7_0.js" %>
<% end %>

<script>
  function executeTest(targetClasses) {
	var startTime = new Date().getTime();
	for(var i = 0; i < targetClasses.length; i++) {
		var $elem = $$(targetClasses[i]);
	}
	var endTime = new Date().getTime();
	
	return endTime - startTime;
  }

  document.observe('dom:loaded', function() {
	var targetClasses = [];
	
	for (var i = 0; i < testData.elements; i++) {
	  $$('body')[0].insert(new Element("div", {'class': 'target_' + i}).update("Example"));
	  targetClasses.push(".target_" + i);
	}
	
	var executionTime = executeTest(targetClasses);

	testData.duration = executionTime;
	testData.name = "Finding";
	testData.framework = "Prototype";
	testHelper.finished();
  });
</script>

app/views/test_runner/_test_prototype_insertion.html.erb
<% content_for :javascript do %>
	<% #<%= javascript_include_tag "frameworks/jquery-1.7.1.js" %>
	<% #<%= javascript_include_tag "frameworks/mootools-core-1.4.4-full-nocompat.js" %>
	<%= javascript_include_tag "frameworks/prototype_1_7_0.js" %>
<% end %>

<script>
  function executeTest() {
    var bodyElement = $$('body')[0];
	var startTime = new Date().getTime();
	
	for (var i = 0; i < testData.elements; i++) {
	    var element = new Element("div").update("Example");
		bodyElement.insert(element);
	}
	
	var endTime = new Date().getTime();
	
	return endTime - startTime;
  }

  document.observe('dom:loaded', function() {
	var executionTime = executeTest();

	testData.duration = executionTime;
	testData.name = "Insertion";
	testData.framework = "Prototype";
	testHelper.finished();
  });
</script>

app/views/test_runner/_test_prototype_modify.html.erb
<% content_for :javascript do %>
	<% #<%= javascript_include_tag "frameworks/jquery-1.7.1.js" %>
	<% #<%= javascript_include_tag "frameworks/mootools-core-1.4.4-full-nocompat.js" %>
	<%= javascript_include_tag "frameworks/prototype_1_7_0.js" %>
<% end %>

<script>
  function executeTest(colors) {
    var $elem = $$('body div')[0];
	var startTime = new Date().getTime();
	for(var i = 0; i < colors.length; i++) {
		$elem.setStyle({backgroundColor: colors[i]});
	}
	var endTime = new Date().getTime();
	
	return endTime - startTime;
  }

  document.observe('dom:loaded', function() {
	$$('body')[0].insert(new Element("div").update("Example"));
	var colors = testHelper.generateColors(testData.elements);
	var executionTime = executeTest(colors);

	testData.duration = executionTime;
	testData.name = "Modify";
	testData.framework = "Prototype";
	testHelper.finished();
  });
</script>

app/views/test_runner/displayTests.html.erb
<%= content_for :javascript do %>
	<%= javascript_include_tag "frameworks/jquery-1.7.1.js" %>
	<%= javascript_include_tag "testHandler.js" %>
<% end %>

<div class='nav_button'><%= link_to "<< Select Device", select_device_path %></div>

<h1>Tests</h1>
<%
	default_element_num = (session[:numberOfElements].nil?) ? 2000 : session[:numberOfElements];
%>
Elements to test: <%= select_tag "elements", options_for_select([1000, 1250, 1500, 2000, 4000, 8000], [default_element_num]) %>


<div id='test_cases'>
	<h2>jQuery</h2>
	<div id="test_jquery_insertion">jQuery insert elements</div>
	<div id="test_jquery_delete">jQuery delete elements</div>
	<div id="test_jquery_modify">jQuery modify elements</div>
	<div id="test_jquery_finding">jQuery find elements</div>
	
	<h2>Mootools</h2>
	<div id="test_mootools_insertion">Mootools insert elements</div>
	<div id="test_mootools_delete">Mootools delete elements</div>
	<div id="test_mootools_modify">Mootools modify elements</div>
	<div id="test_mootools_finding">Mootools find elements</div>
	
	<h2>Prototype</h2>
	<div id="test_prototype_insertion">Prototype insert elements</div>
	<div id="test_prototype_delete">Prototype delete elements</div>
	<div id="test_prototype_modify">Prototype modify elements</div>
	<div id="test_prototype_finding">Prototype find elements</div>
</div>

app/views/test_runner/run.html.erb
<script type="text/javascript" charset="utf-8">
	var partial = "<%= @partial_name %>";
	testData.elements = <%= @numberOfElements %>;
</script>
<%= render "test_runner/"<<@partial_name %>

app/views/test_runner/selectDevice.html.erb
<h1>Select Device:</h1>

<%= @last_was_success unless @last_was_success.nil? %>

<div class='button'><%= link_to "iPhone", "tests?device=iPhone" %></div>
<div class='button'><%= link_to "Android", "tests?device=Android" %></div>
<div class='button'><%= link_to "N95", "tests?device=N95" %></div>